Configure apt sources

nano /etc/apt/sources.list
deb http://ftp.debian.org/debian bullseye main contrib
deb http://ftp.debian.org/debian bullseye-updates main contrib
deb http://security.debian.org/debian-security bullseye-security main contrib
deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription

nano /etc/apt/sources.list.d/pve-enterprise.list 
# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise